# Generated by Django 5.2.12 on 2026-08-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
