# Generated by Django 5.2.12 on 2026-08-15 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'classroom', 'date'], name='student_att_student_40a169_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='student_att_status_9239ff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='student_mes_recipie_a2d593_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['classroom', 'created_at'], name='student_mes_classro_7c1037_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['student', 'classroom', 'recorded_at'], name='student_per_student_c9325a_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['assessment_type'], name='student_per_assessm_d1f593_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['student', 'status'], name='student_que_student_f176e5_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['classroom', 'status'], name='student_que_classro_d2a351_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('publish_at__isnull', True), ('expires_at__gte', models.F('publish_at')), _connector='OR'), name='announcement_valid_publish_window'),
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', models.F('max_score'))), name='performance_score_lte_max_score'),
        ),
    ]
